### PR TITLE
Why Are You Still Ripping Our Work?

### PR DESCRIPTION
**Pull request by Thrax989**
Why Are You Still Ripping Our Work?

### CODE REVIEW

**Comment by c0pp3r** [comment]
Sorry. Forked this as an example of what not to do since your server is dead. Great job...

**Comment by Thrax989** [comment]
We had a DMCA fileby  darkshado after we banned him we were forced to shut down from the IP / Host.
Even tho he filed a false claim they still took it serious. 

Have to start over from scratch .



https://scontent.xx.fbcdn.net/v/t31.0-8/15776686_1238603186187084_1918540412095115830_o.jpg?oh=38e80047327a393915e44c4c9a2ace27&oe=58E9CC10

**Comment by c0pp3r** [comment]
Good luck with your new server.

**Comment by Thrax989** [comment]
Thank you happy new years to you and your team take care. Miss You Guys. Congrats to your new team on Cuemu as well .

"We've also brought on a new developer - everyone please welcome @c0pp3r to the CUEmu team!"
https://cuemu.com/

**Comment by Ascendt** [comment]
I see you blacked out your name in the image, you need to look right above it and black out your name there also that you missed.

as C0pp3r said, good luck with your new server!

**Comment by c0pp3r** [comment]
Thanks. Happy new year to you as well

**Comment by Thrax989** [comment]
Yes just fyi ban darkshado so he does not ruin all of your hard work as well like he has done to other communties. . forums and server ban id recommend . Here's his ip.

24.65.46.237

I forgot to black out my last name but its fine . Thank you for pointing that out . Take care may the force be with you guys .

**Pull request closed without merging**
